{
 "title": "Solana Main Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(solana_account_balance,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "RPC Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(solana_health_status{job=~\"$instance\"}[$__range]) * 100",
     "legendFormat": "Auto"
    }
   ]
  },
  {
   "title": "Health status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "solana_health_status{job=~\"$instance\"}",
     "legendFormat": "Health status"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_epoch{job=~\"$instance\"}",
     "legendFormat": "Epoch"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 8 },
   "targets": [
    {
     "expr": "solana_sync_status{job=~\"$instance\"}",
     "legendFormat": "Sync status"
    }
   ]
  },
  {
   "title": "Slot processing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "solana_slot_number{job=~\"$instance\"}",
     "legendFormat": "Node slot number"
    },
    {
     "expr": "solana_absolute_slot_number{job=~\"$instance\"}",
     "legendFormat": "Network slot number"
    }
   ]
  },
  {
   "title": "Slot lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "solana_slot_lag{job=~\"$instance\"}",
     "legendFormat": "Slot lag"
    }
   ]
  },
  { "title": "Validator Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Block Production Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_block_production_success{job=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slot Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "solana_slot_time{job=~\"$instance\"}",
     "legendFormat": "Slot Processing Time"
    },
    {
     "expr": "avg(avg_over_time(solana_slot_time{job=~\"$instance\"}[1h]))",
     "legendFormat": "Moving Average (1h)"
    },
    {
     "expr": "max(max_over_time(solana_slot_time{job=~\"$instance\"}[30d]))",
     "legendFormat": "Maximum (30d)"
    }
   ]
  },
  {
   "title": "Leader Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_leader_status{job=\"$instance\"}",
     "legendFormat": "Epoch"
    }
   ]
  },
  {
   "title": "Missed slots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "solana_missed_slots{job=~\"$instance\"}",
     "legendFormat": "Missed slots"
    }
   ]
  },
  {
   "title": "Vote distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "solana_vote_distance{job=~\"$instance\"}",
     "legendFormat": "Vote distance"
    }
   ]
  },
  {
   "title": "Stake",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "solana_total_delegated_stake{job=~\"$instance\"}",
     "legendFormat": "Delegated Stake"
    },
    {
     "expr": "solana_delinquent_stake{job=~\"$instance\"}",
     "legendFormat": "Delinquent Stake"
    },
    {
     "expr": "solana_pending_stake{job=~\"$instance\"}",
     "legendFormat": "Pending Stake"
    }
   ]
  },
  {
   "title": "Account Balance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "solana_account_balance{job=~\"$instance\"}",
     "legendFormat": "Account Balance"
    }
   ]
  },
  {
   "title": "Credits Earned",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "solana_credits_earned{job=~\"$instance\"}",
     "legendFormat": "Credits Earned"
    }
   ]
  }
 ]
}