name: Format

on:
    workflow_call:

jobs:
    format:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12

            - name: Install Dependencies
              run: |
                  pip install poetry
                  poetry install -vv
                  poetry run pre-commit install

            - name: Run Formatting Checks
              run: |
                  # Execute formatting checks via pre-commit (reproducing local workflow)
                  poetry run pre-commit run autopep8 --all-files
                  poetry run pre-commit run prettier --all-files
                  poetry run pre-commit run black --all-files
                  poetry run pre-commit run isort --all-files
